### ISSUE TITLE
Can't change shortcut

### ISSUE THREAD

**Issue by jobe451** [erdostom/LoremGibsonSublime#2]
I can't figure out how to change the shortcut ctrl-shift-L on sublime 3 on windows. Which is unfortunate, because to me ctrl-shift-L is quite an important default shortcut.

Lorem gibson is not visible under Preferences => Package Settings.
The only file I find in AppData\Roaming\Sublime Text 3 is LoremGibson.sublime-package which is binary.

**Comment by erdostom** [comment]
Go to Preferences => Key Bindings -- User

Put in a new entry like this one: 

`{ "keys": ["super+ctrl+y"], "command": "loremgibson"}`

Replace the `super+ctrl+y` with your preferred shortcut.

**Comment by jobe451** [comment]
thanks, this did the trick
